version: "3.7"
services:
  yunding:
    pid: web_tool
    container_name: web_tool
    image: web_tool
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ../:/var/www/html
      - ./logs:/var/log/php/
    env_file:
      - .env
    restart: always